package com.eharmony.matching.featureSpecExtractor.cli

import com.eharmony.aloha.FileLocations
import com.eharmony.aloha.io.StringReadable
import com.eharmony.matching.testhelp.io.{TestWithIoCapture, IoCaptureCompanion}
import org.apache.commons.io.IOUtils
import org.apache.commons.vfs2.VFS
import org.junit.Assert._
import org.junit.Test
import org.junit.runner.RunWith
import org.junit.runners.BlockJUnit4ClassRunner

import scala.util.Properties

/**
 * Created by rdeak on 6/19/15.
 */
object DatasetCliTest extends IoCaptureCompanion

@RunWith(classOf[BlockJUnit4ClassRunner])
class DatasetCliTest extends TestWithIoCapture(DatasetCliTest) {
    @Test def cliTest1(): Unit = {
        val input = Seq(
            "MALE,205,stuff|things",
            "FEMALE,115,"
        ).mkString("\n")

        val expected = Seq(
            "| gender=MALE weight=200 num_likes=14",
            "| gender=FEMALE weight=110 num_likes=0"
        ).mkString("\n")

        val tmpFile = "tmp:out.vw"

        val args = Array[String](
            "-s", "res:com/eharmony/matching/featureSpecExtractor/cli/csv_spec1.js",
            "-c", "res:com/eharmony/matching/featureSpecExtractor/cli/csv_types1.js",
            "--cachedir", FileLocations.testGeneratedClasses.getCanonicalPath,
            "--vw", tmpFile
        )

        val in = System.in
        System.setIn(IOUtils.toInputStream(input))
        DatasetCli.main(args)
        System.setIn(in)
        val out = StringReadable.fromVfs2(VFS.getManager.resolveFile(tmpFile)).trim
        assertEquals(expected, out)
    }

    @Test def cliTest2(): Unit = {

        // These were generated by the src/test/resources/test-protos.jar.
        val input = Seq(
            "CAESBEFsYW4YASUAALhBKg0IARABGQAAAAAAAPA/Kg0IAhACGQAAAAAAAABA",
            "CAESBEthdGUYAioNCAMQAxkAAAAAAAAIQA=="
        ).mkString("\n")

        val expected = Seq(
            "| name=Alan gender=MALE bmi:23 num_photos:2",
            "| name=Kate gender=FEMALE bmi=UNK num_photos"
        ).mkString("\n")

        val tmpFile = "tmp:out.vw"

        val args = Array[String](
            "-s", "res:com/eharmony/matching/featureSpecExtractor/cli/proto_spec1.js",
            "-p", "com.eharmony.aloha.test.proto.Testing.UserProto",
            "--cachedir", FileLocations.testGeneratedClasses.getCanonicalPath,
            "--vw", tmpFile
        )

        println(Properties.javaClassPath)
        val in = System.in
        System.setIn(IOUtils.toInputStream(input))
        DatasetCli.main(args)
        System.setIn(in)
        val out = StringReadable.fromVfs2(VFS.getManager.resolveFile(tmpFile)).trim
        assertEquals(expected, out)
    }
}
