package domain;

// Licensed under the Apache License, Version 2.0
// http://www.apache.org/licenses/LICENSE-2.0.html
//
// AUTOGENERATED BY H2O at 2015-09-18T15:45:31.724-07:00
// 3.2.0.1
//
// Standalone prediction code with sample test data for GLMModel named glm_afa04e31_17ad_4ca6_9bd1_8ab80005ce37
//
// How to download, compile and execute:
//     mkdir tmpdir
//     cd tmpdir
//     curl http://192.168.11.110:54321/3/h2o-genmodel.jar > h2o-genmodel.jar
//     curl http://192.168.11.110:54321/3/Models.java/glm-afa04e31-17ad-4ca6-9bd1-8ab80005ce37 > glm_afa04e31_17ad_4ca6_9bd1_8ab80005ce37.java
//     javac -cp h2o-genmodel.jar -J-Xmx2g -J-XX:MaxPermSize=128m glm_afa04e31_17ad_4ca6_9bd1_8ab80005ce37.java
//
//     (Note:  Try java argument -XX:+PrintCompilation to show runtime JIT compiler behavior.)
import java.util.Map;
import hex.genmodel.GenModel;

public class glm_afa04e31_17ad_4ca6_9bd1_8ab80005ce37 extends GenModel {
    public hex.ModelCategory getModelCategory() { return hex.ModelCategory.Regression; }

    public boolean isSupervised() { return true; }
    public int nfeatures() { return 8; }
    public int nclasses() { return 1; }

    // Names of columns used by model.
    public static final String[] NAMES = NamesHolder_glm_afa04e31_17ad_4ca6_9bd1_8ab80005ce37.VALUES;

    // Column domains. The last array contains domain of response column.
    public static final String[][] DOMAINS = new String[][] {
    /* Sex */ glm_afa04e31_17ad_4ca6_9bd1_8ab80005ce37_ColInfo_0.VALUES,
    /* Length */ null,
    /* Diameter */ null,
    /* Height */ null,
    /* Whole weight */ null,
    /* Shucked weight */ null,
    /* Viscera weight */ null,
    /* Shell weight */ null,
    /* Rings */ null
    };
    // Prior class distribution
    public static final double[] PRIOR_CLASS_DISTRIB = null;
    // Class distribution used for model building
    public static final double[] MODEL_CLASS_DISTRIB = null;

    public glm_afa04e31_17ad_4ca6_9bd1_8ab80005ce37() { super(NAMES,DOMAINS); }
    public String getUUID() { return Long.toString(-1276963155634545896L); }

    // Pass in data in a double[], pre-aligned to the Model's requirements.
    // Jam predictions into the preds[] array; preds[0] is reserved for the
    // main prediction (class for classifiers or value for regression),
    // and remaining columns hold a probability distribution for classifiers.
    public final double[] score0( double[] data, double[] preds ) {
        double eta = 0.0;
        final double [] b = BETA;
        for(int i = 0; i < CATOFFS.length-1; ++i) {
            int ival = (int)data[i];
            if(ival != data[i]) throw new IllegalArgumentException("categorical value out of range");
            ival += CATOFFS[i];
            if(ival < CATOFFS[i + 1])
                eta += b[ival];
        }
        for(int i = 1; i < b.length-1-2; ++i)
            eta += b[2+i]*data[i];
        eta += b[b.length-1]; // reduce intercept
        double mu = hex.genmodel.GenModel.GLM_identityInv(eta);
        preds[0] = mu;
        return preds;
    }
    // The Coefficients
    public static final double[] BETA = {0.0,-0.8257199606345127,0.048589336710687686,0.0,10.257730318325152,10.905035426114544,6.411898751852763,-17.066561775662798,-7.706232264683495,11.591721984154416,3.9185206059454405};
    // Categorical Offsets
    public static final int[] CATOFFS = {0,3};





    // The class representing training column names
    static class NamesHolder_glm_afa04e31_17ad_4ca6_9bd1_8ab80005ce37 implements java.io.Serializable {
        public static final String[] VALUES = new String[8];
        static {
            NamesHolder_glm_afa04e31_17ad_4ca6_9bd1_8ab80005ce37_0.fill(VALUES);
        }
        static final class NamesHolder_glm_afa04e31_17ad_4ca6_9bd1_8ab80005ce37_0 implements java.io.Serializable {
            static final void fill(String[] sa) {
                sa[0] = "Sex";
                sa[1] = "Length";
                sa[2] = "Diameter";
                sa[3] = "Height";
                sa[4] = "Whole weight";
                sa[5] = "Shucked weight";
                sa[6] = "Viscera weight";
                sa[7] = "Shell weight";
            }
        }
    }
    // The class representing column Sex
    static class glm_afa04e31_17ad_4ca6_9bd1_8ab80005ce37_ColInfo_0 implements java.io.Serializable {
        public static final String[] VALUES = new String[3];
        static {
            glm_afa04e31_17ad_4ca6_9bd1_8ab80005ce37_ColInfo_0_0.fill(VALUES);
        }
        static final class glm_afa04e31_17ad_4ca6_9bd1_8ab80005ce37_ColInfo_0_0 implements java.io.Serializable {
            static final void fill(String[] sa) {
                sa[0] = "F";
                sa[1] = "I";
                sa[2] = "M";
            }
        }
    }
}
