/*
  Licensed under the Apache License, Version 2.0
    http://www.apache.org/licenses/LICENSE-2.0.html

  AUTOGENERATED BY H2O at 2017-03-28T14:39:48.423-07:00
  3.8.3.3

  Standalone prediction code with sample test data for GBMModel named gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc

  How to download, compile and execute:
      mkdir tmpdir
      cd tmpdir
      curl http://127.0.0.1:54321/3/h2o-genmodel.jar > h2o-genmodel.jar
      curl http://127.0.0.1:54321/3/Models.java/gbm-00ba3eb1-288d-4c30-ad67-c69293b96efc > gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc.java
      javac -cp h2o-genmodel.jar -J-Xmx2g -J-XX:MaxPermSize=128m gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc.java

     (Note:  Try java argument -XX:+PrintCompilation to show runtime JIT compiler behavior.)
*/
import java.util.Map;
import hex.genmodel.GenModel;
import hex.genmodel.annotations.ModelPojo;

@ModelPojo(name="gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc", algorithm="gbm")
public class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc extends GenModel {
    public hex.ModelCategory getModelCategory() { return hex.ModelCategory.Regression; }

    public boolean isSupervised() { return true; }
    public int nfeatures() { return 5; }
    public int nclasses() { return 1; }

    // Names of columns used by model.
    public static final String[] NAMES = NamesHolder_gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc.VALUES;

    // Column domains. The last array contains domain of response column.
    public static final String[][] DOMAINS = new String[][] {
    /* a */ null,
    /* b */ null,
    /* c */ null,
    /* d */ null,
    /* e */ null,
    /* label */ null
    };
    // Prior class distribution
    public static final double[] PRIOR_CLASS_DISTRIB = {1.0};
    // Class distribution used for model building
    public static final double[] MODEL_CLASS_DISTRIB = {1.0};

    public gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc() { super(NAMES,DOMAINS); }
    public String getUUID() { return Long.toString(-3494672109457917612L); }

    // Pass in data in a double[], pre-aligned to the Model's requirements.
    // Jam predictions into the preds[] array; preds[0] is reserved for the
    // main prediction (class for classifiers or value for regression),
    // and remaining columns hold a probability distribution for classifiers.
    public final double[] score0( double[] data, double[] preds ) {
        java.util.Arrays.fill(preds,0);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_0.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_1.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_2.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_3.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_4.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_5.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_6.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_7.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_8.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_9.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_10.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_11.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_12.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_13.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_14.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_15.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_16.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_17.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_18.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_19.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_20.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_21.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_22.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_23.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_24.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_25.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_26.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_27.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_28.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_29.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_30.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_31.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_32.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_33.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_34.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_35.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_36.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_37.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_38.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_39.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_40.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_41.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_42.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_43.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_44.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_45.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_46.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_47.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_48.score0(data,preds);
        gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_49.score0(data,preds);
        preds[0] += 0.5;
        preds[0] = preds[0];
        return preds;
    }
}
// The class representing training column names
class NamesHolder_gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc implements java.io.Serializable {
    public static final String[] VALUES = new String[5];
    static {
        NamesHolder_gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_0.fill(VALUES);
    }
    static final class NamesHolder_gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_0 implements java.io.Serializable {
        static final void fill(String[] sa) {
            sa[0] = "a";
            sa[1] = "b";
            sa[2] = "c";
            sa[3] = "d";
            sa[4] = "e";
        }
    }
}

class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_0 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_0_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_0_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[4 /* e */] <-0.5748447f ?
                (Double.isNaN(data[2]) || data[2 /* c */] <-0.9873447f ?
                        -0.05f :
                        -0.03f) :
                (data[2 /* c */] <0.13970044f ?
                        (data[1 /* b */] <-1.3530363f ?
                                0.05f :
                                0.032352943f) :
                        (Double.isNaN(data[1]) || data[1 /* b */] <0.26298907f ?
                                (Double.isNaN(data[3]) || data[3 /* d */] <0.48426113f ?
                                        -0.05f :
                                        -0.04f) :
                                0.044444446f)));
        return pred;
    } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_1 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_1_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_1_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[4 /* e */] <-0.5748447f ?
                (Double.isNaN(data[4]) || data[4 /* e */] <-1.2645746f ?
                        -0.045666665f :
                        -0.025799999f) :
                (data[2 /* c */] <-0.12864363f ?
                        (data[2 /* c */] <-1.7795287f ?
                                0.03535294f :
                                0.04610294f) :
                        (Double.isNaN(data[1]) || data[1 /* b */] <0.055806328f ?
                                (data[2 /* c */] <0.6386197f ?
                                        -0.019470587f :
                                        -0.039375f) :
                                (data[3 /* d */] <1.3483078f ?
                                        0.045797385f :
                                        0.035555556f))));
        return pred;
    } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_2 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_2_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_2_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[4 /* e */] <-0.5748447f ?
                (Double.isNaN(data[4]) || data[4 /* e */] <-1.2645746f ?
                        -0.0411f :
                        -0.02322f) :
                (data[2 /* c */] <0.13970044f ?
                        (data[1 /* b */] <-1.3530363f ?
                                0.041746873f :
                                0.0257946f) :
                        (Double.isNaN(data[1]) || data[1 /* b */] <0.26298907f ?
                                (data[4 /* e */] <2.1062362f ?
                                        -0.0318625f :
                                        -0.042149063f) :
                                0.03598925f)));
        return pred;
    } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_3 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_3_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_3_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[4 /* e */] <-0.5748447f ?
                (Double.isNaN(data[2]) || data[2 /* c */] <-0.9873447f ?
                        -0.037581556f :
                        -0.0198332f) :
                (data[2 /* c */] <-0.12864363f ?
                        (data[2 /* c */] <-1.7795287f ?
                                0.027962005f :
                                0.038314976f) :
                        (Double.isNaN(data[1]) || data[1 /* b */] <-0.20662513f ?
                                (Double.isNaN(data[1]) || data[1 /* b */] <-0.8711425f ?
                                        -0.020770695f :
                                        -0.03965629f) :
                                (Double.isNaN(data[0]) || data[0 /* a */] <0.9789278f ?
                                        0.03881934f :
                                        0.02036609f))));
        return pred;
    } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_4 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_4_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_4_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[4 /* e */] <-0.5748447f ?
                (Double.isNaN(data[4]) || data[4 /* e */] <-1.2645746f ?
                        -0.033823457f :
                        -0.017849777f) :
                (data[2 /* c */] <0.13970044f ?
                        (data[1 /* b */] <-1.3530363f ?
                                0.03499691f :
                                0.020302754f) :
                        (Double.isNaN(data[1]) || data[1 /* b */] <0.26298907f ?
                                (data[2 /* c */] <0.97904927f ?
                                        -0.036019143f :
                                        -0.026122274f) :
                                0.02943106f)));
        return pred;
    } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_5 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_5_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_5_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[4 /* e */] <-0.5748447f ?
                (Double.isNaN(data[2]) || data[2 /* c */] <-0.9873447f ?
                        -0.030973509f :
                        -0.0151064815f) :
                (data[2 /* c */] <-0.12864363f ?
                        (data[2 /* c */] <-1.7795287f ?
                                0.021959992f :
                                0.031902168f) :
                        (Double.isNaN(data[1]) || data[1 /* b */] <0.055806328f ?
                                (Double.isNaN(data[0]) || data[0 /* a */] <1.7694315f ?
                                        -0.015282403f :
                                        -0.029305233f) :
                                (data[1 /* b */] <1.247107f ?
                                        0.021754047f :
                                        0.03266293f))));
        return pred;
    } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_6 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_6_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_6_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[4 /* e */] <-0.5748447f ?
                (Double.isNaN(data[2]) || data[2 /* c */] <-0.9873447f ?
                        -0.027876157f :
                        -0.013595833f) :
                (data[2 /* c */] <0.13970044f ?
                        (data[1 /* b */] <-1.3530363f ?
                                0.029481554f :
                                0.016316257f) :
                        (Double.isNaN(data[1]) || data[1 /* b */] <0.26298907f ?
                                (data[2 /* c */] <0.97904927f ?
                                        -0.030047618f :
                                        -0.021599365f) :
                                0.023706503f)));
        return pred;
    } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_7 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_7_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_7_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[4 /* e */] <-0.5748447f ?
                (Double.isNaN(data[4]) || data[4 /* e */] <-1.2645746f ?
                        -0.025561055f :
                        -0.011385727f) :
                (Double.isNaN(data[4]) || data[4 /* e */] <1.2250006f ?
                        (data[1 /* b */] <-0.6762393f ?
                                5.5718573E-4f :
                                (data[2 /* c */] <0.28537294f ?
                                        0.030212857f :
                                        0.026776638f)) :
                        (data[3 /* d */] <-0.8867023f ?
                                0.026100047f :
                                (data[4 /* e */] <2.2333162f ?
                                        -0.012338629f :
                                        -0.02510172f))));
        return pred;
    } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_8 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_8_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_8_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[4 /* e */] <-0.5748447f ?
                (Double.isNaN(data[4]) || data[4 /* e */] <-1.2645746f ?
                        -0.02300495f :
                        -0.010247154f) :
                (data[2 /* c */] <0.13970044f ?
                        (data[1 /* b */] <-1.3530363f ?
                                0.02488198f :
                                0.013036081f) :
                        (Double.isNaN(data[1]) || data[1 /* b */] <0.26298907f ?
                                (data[2 /* c */] <0.97904927f ?
                                        -0.025172165f :
                                        -0.01809316f) :
                                0.019310113f)));
        return pred;
    } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_9 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_9_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_9_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[4 /* e */] <-0.5748447f ?
                (Double.isNaN(data[2]) || data[2 /* c */] <-0.9873447f ?
                        -0.02112971f :
                        -0.008456976f) :
                (Double.isNaN(data[4]) || data[4 /* e */] <1.2250006f ?
                        (data[1 /* b */] <-0.6762393f ?
                                -1.00369754E-4f :
                                (data[3 /* d */] <0.21826294f ?
                                        0.02588796f :
                                        0.022167966f)) :
                        (data[3 /* d */] <-0.8867023f ?
                                0.021100562f :
                                (Double.isNaN(data[2]) || data[2 /* c */] <0.97129416f ?
                                        -0.02184477f :
                                        -0.010578136f))));
        return pred;
    } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_10 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_10_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_10_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[4 /* e */] <-0.5748447f ?
                (Double.isNaN(data[2]) || data[2 /* c */] <-0.9873447f ?
                        -0.01901674f :
                        -0.0076112784f) :
                (data[2 /* c */] <0.13970044f ?
                        (Double.isNaN(data[1]) || data[1 /* b */] <-0.6624271f ?
                                (Double.isNaN(data[1]) || data[1 /* b */] <-1.5170559f ?
                                        0.021633996f :
                                        -2.2895992E-4f) :
                                0.023259938f) :
                        (Double.isNaN(data[1]) || data[1 /* b */] <0.26298907f ?
                                (Double.isNaN(data[1]) || data[1 /* b */] <-0.86886543f ?
                                        -0.014643707f :
                                        -0.021642802f) :
                                0.015708072f)));
        return pred;
    } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_11 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_11_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_11_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[4 /* e */] <-0.5748447f ?
                (Double.isNaN(data[4]) || data[4 /* e */] <-1.2645746f ?
                        -0.017492415f :
                        -0.0061709215f) :
                (Double.isNaN(data[4]) || data[4 /* e */] <1.2250006f ?
                        (data[0 /* a */] <0.26411065f ?
                                5.153309E-4f :
                                (data[2 /* c */] <0.28537294f ?
                                        0.02226258f :
                                        0.018435419f)) :
                        (data[3 /* d */] <-0.8867023f ?
                                0.017177938f :
                                (data[4 /* e */] <2.2333162f ?
                                        -0.008115565f :
                                        -0.018140603f))));
        return pred;
    } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_12 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_12_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_12_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[0 /* a */] <0.29727355f ?
                (Double.isNaN(data[2]) || data[2 /* c */] <0.024695834f ?
                        (Double.isNaN(data[2]) || data[2 /* c */] <-1.1816727f ?
                                -0.01638445f :
                                0.013293444f) :
                        -0.02119628f) :
                (Double.isNaN(data[4]) || data[4 /* e */] <1.987553f ?
                        (Double.isNaN(data[2]) || data[2 /* c */] <1.435419f ?
                                (data[4 /* e */] <0.6037603f ?
                                        0.0167882f :
                                        0.024588184f) :
                                1.9430608E-4f) :
                        (Double.isNaN(data[1]) || data[1 /* b */] <-1.3530363f ?
                                0.009119822f :
                                -0.021748798f)));
        return pred;
    } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_13 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_13_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_13_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[4 /* e */] <-0.5748447f ?
                (Double.isNaN(data[4]) || data[4 /* e */] <-1.2645746f ?
                        -0.014684041f :
                        -0.004709484f) :
                (Double.isNaN(data[4]) || data[4 /* e */] <1.2250006f ?
                        (data[1 /* b */] <-0.6762393f ?
                                -6.726647E-4f :
                                (data[0 /* a */] <0.44321075f ?
                                        0.018099278f :
                                        0.015886739f)) :
                        (data[3 /* d */] <-0.8867023f ?
                                0.014032552f :
                                (Double.isNaN(data[2]) || data[2 /* c */] <0.97129416f ?
                                        -0.015543184f :
                                        -0.007426062f))));
        return pred;
    } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_14 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_14_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_14_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[0 /* a */] <0.29727355f ?
                (Double.isNaN(data[2]) || data[2 /* c */] <0.024695834f ?
                        (Double.isNaN(data[2]) || data[2 /* c */] <-1.1816727f ?
                                -0.013710355f :
                                0.011978044f) :
                        -0.018568054f) :
                (Double.isNaN(data[4]) || data[4 /* e */] <1.987553f ?
                        (Double.isNaN(data[2]) || data[2 /* c */] <1.435419f ?
                                (data[4 /* e */] <0.6037603f ?
                                        0.013440251f :
                                        0.021645254f) :
                                -7.3653937E-4f) :
                        (Double.isNaN(data[1]) || data[1 /* b */] <-1.3530363f ?
                                0.007722801f :
                                -0.018240977f)));
        return pred;
    } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_15 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_15_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_15_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[4 /* e */] <-1.2645668f ?
                -0.012334493f :
                (Double.isNaN(data[1]) || data[1 /* b */] <0.71385574f ?
                        (Double.isNaN(data[3]) || data[3 /* d */] <0.7460075f ?
                                (Double.isNaN(data[1]) || data[1 /* b */] <-0.8547875f ?
                                        (Double.isNaN(data[3]) || data[3 /* d */] <-0.87730134f ?
                                                0.017544247f :
                                                -0.0056439536f) :
                                        (data[3 /* d */] <-0.7499994f ?
                                                -0.019667087f :
                                                0.005561741f)) :
                                -0.023384552f) :
                        0.01911537f));
        return pred;
    } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_16 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_16_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_16_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[4 /* e */] <-1.2645668f ?
                -0.011101043f :
                (Double.isNaN(data[1]) || data[1 /* b */] <0.71385574f ?
                        (Double.isNaN(data[2]) || data[2 /* c */] <0.71472347f ?
                                (data[1 /* b */] <-0.94052005f ?
                                        (Double.isNaN(data[2]) || data[2 /* c */] <-0.9014991f ?
                                                0.016639229f :
                                                0.002074451f) :
                                        (data[3 /* d */] <-0.7314332f ?
                                                -0.017700378f :
                                                0.009043436f)) :
                                -0.015032232f) :
                        0.01720383f));
        return pred;
    } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_17 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_17_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_17_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[4 /* e */] <-1.2645668f ?
                -0.009990939f :
                (Double.isNaN(data[1]) || data[1 /* b */] <0.71385574f ?
                        (Double.isNaN(data[3]) || data[3 /* d */] <0.7460075f ?
                                (Double.isNaN(data[0]) || data[0 /* a */] <1.864255f ?
                                        (data[2 /* c */] <-1.0860641f ?
                                                -0.0012191109f :
                                                0.011574235f) :
                                        -0.0073610824f) :
                                -0.019783631f) :
                        0.01548345f));
        return pred;
    } // constant pool size = 22B, number of visited nodes = 5, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_18 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_18_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_18_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[4 /* e */] <-1.2645668f ?
                -0.008991845f :
                (Double.isNaN(data[1]) || data[1 /* b */] <0.71385574f ?
                        (Double.isNaN(data[2]) || data[2 /* c */] <0.1473674f ?
                                (Double.isNaN(data[1]) || data[1 /* b */] <-0.87193406f ?
                                        (Double.isNaN(data[0]) || data[0 /* a */] <1.1984789f ?
                                                0.018175721f :
                                                0.0076220296f) :
                                        -0.0031106593f) :
                                (data[1 /* b */] <-0.8890805f ?
                                        -0.01711049f :
                                        -0.0046540806f)) :
                        0.013935106f));
        return pred;
    } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_19 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_19_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_19_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[4 /* e */] <-1.2645668f ?
                -0.00809266f :
                (Double.isNaN(data[1]) || data[1 /* b */] <0.77603835f ?
                        (Double.isNaN(data[3]) || data[3 /* d */] <0.7460075f ?
                                (Double.isNaN(data[0]) || data[0 /* a */] <1.864255f ?
                                        (data[2 /* c */] <-1.0860641f ?
                                                -0.0017928166f :
                                                0.01046687f) :
                                        -0.0064948145f) :
                                -0.016841603f) :
                        0.013007508f));
        return pred;
    } // constant pool size = 22B, number of visited nodes = 5, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_20 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_20_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_20_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[0 /* a */] <0.29727355f ?
                (Double.isNaN(data[2]) || data[2 /* c */] <0.024695834f ?
                        (Double.isNaN(data[2]) || data[2 /* c */] <-1.0731633f ?
                                (data[1 /* b */] <0.66165316f ?
                                        -0.011336573f :
                                        -0.0031483923f) :
                                0.0111869285f) :
                        -0.012325324f) :
                (Double.isNaN(data[4]) || data[4 /* e */] <1.987553f ?
                        (Double.isNaN(data[2]) || data[2 /* c */] <1.3434153f ?
                                (data[1 /* b */] <-0.40163323f ?
                                        0.017130798f :
                                        0.009260322f) :
                                -0.0030348017f) :
                        (Double.isNaN(data[1]) || data[1 /* b */] <-1.3530363f ?
                                0.005107158f :
                                -0.013627083f)));
        return pred;
    } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_21 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_21_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_21_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[4 /* e */] <-1.8139384f ?
                -0.008362916f :
                (Double.isNaN(data[2]) || data[2 /* c */] <1.2974135f ?
                        (Double.isNaN(data[4]) || data[4 /* e */] <2.0005467f ?
                                (data[2 /* c */] <-1.0221903f ?
                                        (data[4 /* e */] <-0.49620408f ?
                                                -0.00935227f :
                                                0.004072157f) :
                                        (data[2 /* c */] <-2.8167965E-4f ?
                                                0.019873966f :
                                                0.007020108f)) :
                                (Double.isNaN(data[1]) || data[1 /* b */] <-1.339227f ?
                                        0.006895409f :
                                        -0.013215839f)) :
                        -0.006400979f));
        return pred;
    } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_22 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_22_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_22_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[4 /* e */] <-1.8139384f ?
                -0.0075266245f :
                (Double.isNaN(data[1]) || data[1 /* b */] <0.77603835f ?
                        (Double.isNaN(data[3]) || data[3 /* d */] <0.7460075f ?
                                (Double.isNaN(data[1]) || data[1 /* b */] <-0.85675067f ?
                                        (Double.isNaN(data[3]) || data[3 /* d */] <-0.87730134f ?
                                                0.011574911f :
                                                -0.004421363f) :
                                        (data[3 /* d */] <-0.7499994f ?
                                                -0.011836588f :
                                                0.0035182869f)) :
                                -0.014034788f) :
                        0.009215326f));
        return pred;
    } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_23 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_23_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_23_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[4 /* e */] <-1.5933877f ?
                -0.006279699f :
                (Double.isNaN(data[1]) || data[1 /* b */] <0.71385574f ?
                        (Double.isNaN(data[2]) || data[2 /* c */] <0.1473674f ?
                                (Double.isNaN(data[1]) || data[1 /* b */] <-0.87193406f ?
                                        (Double.isNaN(data[0]) || data[0 /* a */] <1.1984789f ?
                                                0.013175814f :
                                                0.005365256f) :
                                        -0.0031635303f) :
                                (data[1 /* b */] <-0.8890805f ?
                                        -0.01350045f :
                                        -0.0024091806f)) :
                        0.009466046f));
        return pred;
    } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_24 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_24_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_24_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[2]) || data[2 /* c */] <1.2935799f ?
                (data[4 /* e */] <-1.2605567f ?
                        -0.005209646f :
                        (Double.isNaN(data[4]) || data[4 /* e */] <1.8965759f ?
                                (data[2 /* c */] <-0.9780593f ?
                                        -0.00239349f :
                                        (data[2 /* c */] <0.024197256f ?
                                                0.018623048f :
                                                0.006293347f)) :
                                (data[1 /* b */] <-1.3792589f ?
                                        0.006305817f :
                                        -0.01007616f))) :
                -0.0055650203f);
        return pred;
    } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_25 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_25_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_25_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[0 /* a */] <0.29727355f ?
                (Double.isNaN(data[2]) || data[2 /* c */] <0.024695834f ?
                        (Double.isNaN(data[2]) || data[2 /* c */] <-1.1816727f ?
                                -0.0053928797f :
                                0.0071331807f) :
                        -0.009401793f) :
                (Double.isNaN(data[4]) || data[4 /* e */] <1.987553f ?
                        (Double.isNaN(data[2]) || data[2 /* c */] <1.3434153f ?
                                (Double.isNaN(data[2]) || data[2 /* c */] <0.047576953f ?
                                        0.006216178f :
                                        0.013131011f) :
                                -0.0023440614f) :
                        (Double.isNaN(data[1]) || data[1 /* b */] <-1.3530363f ?
                                0.0029397367f :
                                -0.00949551f)));
        return pred;
    } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_26 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_26_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_26_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[4 /* e */] <-1.8139384f ?
                -0.005357722f :
                (Double.isNaN(data[1]) || data[1 /* b */] <0.71385574f ?
                        (Double.isNaN(data[3]) || data[3 /* d */] <0.7460075f ?
                                (Double.isNaN(data[1]) || data[1 /* b */] <-0.8547875f ?
                                        (data[4 /* e */] <1.7618906f ?
                                                0.0122531885f :
                                                -7.2040386E-4f) :
                                        (data[3 /* d */] <-0.7499994f ?
                                                -0.01134807f :
                                                0.002704754f)) :
                                -0.011123349f) :
                        0.007278808f));
        return pred;
    } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_27 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_27_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_27_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[2]) || data[2 /* c */] <1.2935799f ?
                (data[4 /* e */] <-1.5973978f ?
                        -0.0044516455f :
                        (Double.isNaN(data[4]) || data[4 /* e */] <1.8943202f ?
                                (data[2 /* c */] <-0.9780593f ?
                                        -0.0020532857f :
                                        (data[2 /* c */] <0.024197256f ?
                                                0.015717449f :
                                                0.0046190047f)) :
                                (data[1 /* b */] <-1.3792589f ?
                                        0.005420534f :
                                        -0.008336901f))) :
                -0.0044119023f);
        return pred;
    } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_28 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_28_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_28_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[0 /* a */] <0.29727355f ?
                (Double.isNaN(data[2]) || data[2 /* c */] <0.024695834f ?
                        (Double.isNaN(data[2]) || data[2 /* c */] <-1.0731633f ?
                                (data[4 /* e */] <-1.3450787f ?
                                        9.96411E-4f :
                                        -0.008146004f) :
                                0.00658976f) :
                        -0.008165288f) :
                (Double.isNaN(data[4]) || data[4 /* e */] <1.987553f ?
                        (Double.isNaN(data[3]) || data[3 /* d */] <0.8284676f ?
                                0.008531117f :
                                -7.037256E-4f) :
                        (Double.isNaN(data[1]) || data[1 /* b */] <-1.3530363f ?
                                0.0024869759f :
                                -0.00767155f)));
        return pred;
    } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_29 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_29_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_29_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[4 /* e */] <-1.8139384f ?
                -0.004439914f :
                (Double.isNaN(data[1]) || data[1 /* b */] <0.77603835f ?
                        (Double.isNaN(data[3]) || data[3 /* d */] <0.7460075f ?
                                (Double.isNaN(data[1]) || data[1 /* b */] <-0.85675067f ?
                                        (data[4 /* e */] <1.7618906f ?
                                                0.010589217f :
                                                -8.507249E-4f) :
                                        (data[3 /* d */] <-0.7499994f ?
                                                -0.008704539f :
                                                0.0018023632f)) :
                                -0.009329661f) :
                        0.0069124796f));
        return pred;
    } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_30 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_30_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_30_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[4 /* e */] <-1.5933877f ?
                -0.0037720874f :
                (Double.isNaN(data[1]) || data[1 /* b */] <0.77603835f ?
                        (Double.isNaN(data[2]) || data[2 /* c */] <0.1473674f ?
                                (Double.isNaN(data[1]) || data[1 /* b */] <-0.8740943f ?
                                        (Double.isNaN(data[2]) || data[2 /* c */] <-1.1944162f ?
                                                0.0038362362f :
                                                0.009533615f) :
                                        (data[2 /* c */] <-0.8831598f ?
                                                -0.007867018f :
                                                0.0021270586f)) :
                                (data[1 /* b */] <-0.89143795f ?
                                        -0.010299464f :
                                        -9.79947E-4f)) :
                        0.0073447623f));
        return pred;
    } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_31 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_31_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_31_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[2]) || data[2 /* c */] <1.2935799f ?
                (Double.isNaN(data[3]) || data[3 /* d */] <0.68828547f ?
                        (Double.isNaN(data[2]) || data[2 /* c */] <0.610657f ?
                                (Double.isNaN(data[2]) || data[2 /* c */] <-0.09061232f ?
                                        (data[1 /* b */] <-0.8821637f ?
                                                0.0035857365f :
                                                -0.0039750184f) :
                                        0.009379316f) :
                                -0.007111142f) :
                        0.0068951687f) :
                -0.003658275f);
        return pred;
    } // constant pool size = 22B, number of visited nodes = 5, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_32 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_32_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_32_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[2]) || data[2 /* c */] <1.2935799f ?
                (Double.isNaN(data[3]) || data[3 /* d */] <0.68828547f ?
                        (Double.isNaN(data[2]) || data[2 /* c */] <0.13624863f ?
                                (data[1 /* b */] <-0.8821637f ?
                                        (Double.isNaN(data[2]) || data[2 /* c */] <-1.1944162f ?
                                                0.0030940392f :
                                                0.008105805f) :
                                        (data[2 /* c */] <-1.6440085f ?
                                                -0.0059185503f :
                                                9.362029E-4f)) :
                                -0.0052967425f) :
                        0.0062056514f) :
                -0.0032924463f);
        return pred;
    } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_33 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_33_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_33_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[1]) || data[1 /* b */] <0.71385574f ?
                (Double.isNaN(data[3]) || data[3 /* d */] <0.7460075f ?
                        (Double.isNaN(data[1]) || data[1 /* b */] <-0.7947748f ?
                                (Double.isNaN(data[1]) || data[1 /* b */] <-1.2602421f ?
                                        (Double.isNaN(data[1]) || data[1 /* b */] <-1.7369735f ?
                                                0.0017341457f :
                                                -0.005536981f) :
                                        0.011540286f) :
                                (data[2 /* c */] <-0.685919f ?
                                        -0.008394552f :
                                        7.3889137E-4f)) :
                        -0.007631878f) :
                (Double.isNaN(data[4]) || data[4 /* e */] <-1.1803565f ?
                        -0.0023869686f :
                        0.007003456f));
        return pred;
    } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_34 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_34_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_34_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[2]) || data[2 /* c */] <0.05536373f ?
                (data[1 /* b */] <-0.8821637f ?
                        (Double.isNaN(data[4]) || data[4 /* e */] <2.2361739f ?
                                0.006996277f :
                                0.0024149842f) :
                        (Double.isNaN(data[2]) || data[2 /* c */] <-0.66700965f ?
                                (data[1 /* b */] <0.64821625f ?
                                        -0.007555098f :
                                        -7.2304116E-5f) :
                                0.0039564394f)) :
                (data[1 /* b */] <-0.9098004f ?
                        -0.009352466f :
                        (Double.isNaN(data[4]) || data[4 /* e */] <1.7191259f ?
                                (data[1 /* b */] <0.85239923f ?
                                        -0.007110944f :
                                        0.0021972277f) :
                                0.005815903f)));
        return pred;
    } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_35 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_35_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_35_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[4]) || data[4 /* e */] <1.8913127f ?
                (Double.isNaN(data[3]) || data[3 /* d */] <0.7789916f ?
                        (Double.isNaN(data[2]) || data[2 /* c */] <-0.09797574f ?
                                (Double.isNaN(data[4]) || data[4 /* e */] <0.032665912f ?
                                        (Double.isNaN(data[4]) || data[4 /* e */] <-1.1161069f ?
                                                9.933377E-4f :
                                                -0.0071559907f) :
                                        0.0049077887f) :
                                0.009100204f) :
                        (data[1 /* b */] <1.2454423f ?
                                -0.007992876f :
                                0.0025295794f)) :
                (data[1 /* b */] <-1.5316262f ?
                        0.0032091183f :
                        -0.006292749f));
        return pred;
    } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_36 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_36_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_36_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[4 /* e */] <-1.8139384f ?
                -0.0033811696f :
                (data[0 /* a */] <-0.40367797f ?
                        0.0071957908f :
                        (Double.isNaN(data[3]) || data[3 /* d */] <0.6965315f ?
                                (Double.isNaN(data[2]) || data[2 /* c */] <0.16270135f ?
                                        (data[1 /* b */] <-1.3457385f ?
                                                0.003884315f :
                                                -0.0025043755f) :
                                        -0.0054277955f) :
                                (data[2 /* c */] <1.5427566f ?
                                        0.008377432f :
                                        -0.0020671692f))));
        return pred;
    } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_37 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_37_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_37_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[4]) || data[4 /* e */] <0.7685093f ?
                (data[4 /* e */] <-1.5937793f ?
                        -0.0027785029f :
                        (data[2 /* c */] <-1.141603f ?
                                -0.0042466116f :
                                (data[2 /* c */] <0.019681247f ?
                                        0.013354528f :
                                        0.0013296185f))) :
                (data[0 /* a */] <0.8580348f ?
                        -0.007903642f :
                        (data[1 /* b */] <-0.8696099f ?
                                0.003150362f :
                                -0.0023694523f)));
        return pred;
    } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_38 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_38_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_38_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[4]) || data[4 /* e */] <1.8913127f ?
                (Double.isNaN(data[3]) || data[3 /* d */] <0.7789916f ?
                        (Double.isNaN(data[0]) || data[0 /* a */] <0.5981065f ?
                                (Double.isNaN(data[0]) || data[0 /* a */] <-0.11642195f ?
                                        (Double.isNaN(data[4]) || data[4 /* e */] <-1.6018335f ?
                                                -0.0019751873f :
                                                0.0087291775f) :
                                        -0.0025141116f) :
                                0.009231504f) :
                        (data[1 /* b */] <1.2454423f ?
                                -0.00760134f :
                                0.0023767466f)) :
                (data[1 /* b */] <-1.5316262f ?
                        0.0024989422f :
                        -0.005396516f));
        return pred;
    } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_39 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_39_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_39_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[1 /* b */] <-1.1550761f ?
                (Double.isNaN(data[4]) || data[4 /* e */] <2.685295f ?
                        -0.004490441f :
                        0.0013364948f) :
                (data[1 /* b */] <-0.8366333f ?
                        0.009385078f :
                        (Double.isNaN(data[1]) || data[1 /* b */] <0.7094176f ?
                                (data[2 /* c */] <-0.6715452f ?
                                        -0.0063448013f :
                                        (Double.isNaN(data[4]) || data[4 /* e */] <1.0030364f ?
                                                0.0031127369f :
                                                -0.0077143162f)) :
                                (data[0 /* a */] <-1.0319382f ?
                                        -0.0036319438f :
                                        (data[4 /* e */] <-0.13975982f ?
                                                0.0065006237f :
                                                0.002587909f)))));
        return pred;
    } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_40 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_40_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_40_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[2 /* c */] <-0.082641795f ?
                (Double.isNaN(data[2]) || data[2 /* c */] <-0.787045f ?
                        (data[0 /* a */] <-0.6013287f ?
                                0.006556858f :
                                (data[4 /* e */] <0.19908763f ?
                                        -0.0066140294f :
                                        0.0026550977f)) :
                        -0.0064507527f) :
                (data[2 /* c */] <0.48016196f ?
                        0.008226058f :
                        (Double.isNaN(data[4]) || data[4 /* e */] <1.7118977f ?
                                (Double.isNaN(data[1]) || data[1 /* b */] <0.85172063f ?
                                        -0.0066372086f :
                                        0.0021968791f) :
                                0.0037388387f)));
        return pred;
    } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_41 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_41_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_41_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[4]) || data[4 /* e */] <1.8913127f ?
                (Double.isNaN(data[3]) || data[3 /* d */] <0.7789916f ?
                        (Double.isNaN(data[2]) || data[2 /* c */] <-0.09797574f ?
                                (Double.isNaN(data[4]) || data[4 /* e */] <0.032665912f ?
                                        (Double.isNaN(data[4]) || data[4 /* e */] <-1.1161069f ?
                                                0.0010562346f :
                                                -0.005935503f) :
                                        0.003986401f) :
                                0.0075508305f) :
                        (data[1 /* b */] <1.2454423f ?
                                -0.0063511543f :
                                0.0017039283f)) :
                (data[1 /* b */] <-1.5316262f ?
                        0.0020396844f :
                        -0.004844204f));
        return pred;
    } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_42 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_42_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_42_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[3 /* d */] <-2.449321f ?
                -0.0033937334f :
                (data[3 /* d */] <-0.851689f ?
                        (data[1 /* b */] <-0.30293822f ?
                                0.007831706f :
                                4.6293464E-4f) :
                        (data[2 /* c */] <-0.081079856f ?
                                -0.006315849f :
                                (Double.isNaN(data[3]) || data[3 /* d */] <0.8562277f ?
                                        (data[4 /* e */] <1.8790046f ?
                                                0.005950269f :
                                                -1.6089267E-4f) :
                                        (data[1 /* b */] <1.2352669f ?
                                                -0.005868096f :
                                                0.0015335359f)))));
        return pred;
    } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_43 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_43_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_43_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[1 /* b */] <-1.1550761f ?
                (Double.isNaN(data[4]) || data[4 /* e */] <2.685295f ?
                        -0.004367885f :
                        0.0010579788f) :
                (data[1 /* b */] <-0.8366333f ?
                        0.008288991f :
                        (Double.isNaN(data[1]) || data[1 /* b */] <0.7094176f ?
                                (Double.isNaN(data[1]) || data[1 /* b */] <0.20842864f ?
                                        (data[3 /* d */] <-0.46622908f ?
                                                -0.003922768f :
                                                0.0015721548f) :
                                        -0.0052134306f) :
                                (Double.isNaN(data[4]) || data[4 /* e */] <-1.1847169f ?
                                        -0.0017942204f :
                                        0.005040196f))));
        return pred;
    } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_44 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_44_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_44_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[4 /* e */] <-0.03750308f ?
                (data[4 /* e */] <-1.5955925f ?
                        -0.0022110865f :
                        (data[0 /* a */] <-0.36591366f ?
                                0.006723344f :
                                0.002512246f)) :
                (data[0 /* a */] <0.26612014f ?
                        -0.0066484245f :
                        (Double.isNaN(data[4]) || data[4 /* e */] <1.8651305f ?
                                (Double.isNaN(data[3]) || data[3 /* d */] <0.8119756f ?
                                        0.0059312778f :
                                        -0.0031437397f) :
                                (data[2 /* c */] <-0.051973898f ?
                                        -0.0054519526f :
                                        8.20116E-4f))));
        return pred;
    } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_45 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_45_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_45_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[4 /* e */] <-0.03750308f ?
                (data[4 /* e */] <-1.5955925f ?
                        -0.0019899777f :
                        (data[0 /* a */] <-0.36591366f ?
                                0.0060510095f :
                                0.0022610233f)) :
                (data[0 /* a */] <0.26612014f ?
                        -0.0059835827f :
                        (Double.isNaN(data[4]) || data[4 /* e */] <1.8651305f ?
                                (data[1 /* b */] <-0.30331042f ?
                                        0.0073412093f :
                                        -0.0012196695f) :
                                (data[1 /* b */] <-1.5464069f ?
                                        0.0021876802f :
                                        -0.0040487237f))));
        return pred;
    } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_46 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_46_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_46_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[3 /* d */] <-2.449321f ?
                -0.0030647153f :
                (data[3 /* d */] <-0.851689f ?
                        (data[1 /* b */] <-0.30293822f ?
                                0.007055437f :
                                3.6923453E-4f) :
                        (data[1 /* b */] <-0.91775185f ?
                                -0.0058347303f :
                                (data[0 /* a */] <-0.96963143f ?
                                        -0.0039307564f :
                                        (data[0 /* a */] <0.8898372f ?
                                                0.0051718066f :
                                                -0.0018091754f)))));
        return pred;
    } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_47 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_47_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_47_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[4 /* e */] <-1.019956f ?
                (Double.isNaN(data[4]) || data[4 /* e */] <-2.1383734f ?
                        -0.0019578533f :
                        0.006781365f) :
                (Double.isNaN(data[0]) || data[0 /* a */] <1.3876426f ?
                        (Double.isNaN(data[0]) || data[0 /* a */] <0.92400926f ?
                                (Double.isNaN(data[3]) || data[3 /* d */] <0.5798155f ?
                                        (data[1 /* b */] <-0.6667413f ?
                                                -0.007962443f :
                                                1.0989023E-4f) :
                                        0.0038815748f) :
                                -0.0065802615f) :
                        (data[0 /* a */] <2.094983f ?
                                0.0051829168f :
                                -0.0010043064f)));
        return pred;
    } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_48 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_48_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_48_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[3]) || data[3 /* d */] <1.3026131f ?
                (Double.isNaN(data[3]) || data[3 /* d */] <0.69334257f ?
                        (Double.isNaN(data[2]) || data[2 /* c */] <0.3327811f ?
                                (data[0 /* a */] <0.19424422f ?
                                        (Double.isNaN(data[4]) || data[4 /* e */] <-1.2124366f ?
                                                -7.8064203E-4f :
                                                0.0073665907f) :
                                        (data[1 /* b */] <-1.7112647f ?
                                                0.003221736f :
                                                -0.0038957621f)) :
                                -0.004266143f) :
                        0.005984113f) :
                -0.002488804f);
        return pred;
    } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}


class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Forest_49 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_49_class_0.score0(fdata);
    }
}
class gbm_00ba3eb1_288d_4c30_ad67_c69293b96efc_Tree_49_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[3]) || data[3 /* d */] <0.8614516f ?
                (Double.isNaN(data[2]) || data[2 /* c */] <-0.082641795f ?
                        (Double.isNaN(data[2]) || data[2 /* c */] <-0.921217f ?
                                (Double.isNaN(data[0]) || data[0 /* a */] <0.1911179f ?
                                        (data[0 /* a */] <-0.59366363f ?
                                                0.0060511213f :
                                                4.7834858E-4f) :
                                        -0.0021247019f) :
                                -0.005225988f) :
                        (data[0 /* a */] <0.8403236f ?
                                -2.782596E-4f :
                                0.006151251f)) :
                (data[1 /* b */] <1.2458622f ?
                        -0.0059478795f :
                        0.0011934456f));
        return pred;
    } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}
