// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.eharmony.aloha.test.proto;

public final class Testing {
  private Testing() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum GenderProto
      implements com.google.protobuf.ProtocolMessageEnum {
    MALE(0, 1),
    FEMALE(1, 2),
    ;
    
    public static final int MALE_VALUE = 1;
    public static final int FEMALE_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static GenderProto valueOf(int value) {
      switch (value) {
        case 1: return MALE;
        case 2: return FEMALE;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<GenderProto>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<GenderProto>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GenderProto>() {
            public GenderProto findValueByNumber(int number) {
              return GenderProto.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.eharmony.aloha.test.proto.Testing.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final GenderProto[] VALUES = {
      MALE, FEMALE, 
    };
    
    public static GenderProto valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private GenderProto(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.eharmony.aloha.test.proto.GenderProto)
  }
  
  public interface PhotoProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 id = 1;
    boolean hasId();
    long getId();
    
    // optional int32 height = 2;
    boolean hasHeight();
    int getHeight();
    
    // optional double aspect_ratio = 3;
    boolean hasAspectRatio();
    double getAspectRatio();
  }
  public static final class PhotoProto extends
      com.google.protobuf.GeneratedMessage
      implements PhotoProtoOrBuilder {
    // Use PhotoProto.newBuilder() to construct.
    private PhotoProto(Builder builder) {
      super(builder);
    }
    private PhotoProto(boolean noInit) {}
    
    private static final PhotoProto defaultInstance;
    public static PhotoProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public PhotoProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.eharmony.aloha.test.proto.Testing.internal_static_com_eharmony_aloha_test_proto_PhotoProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.eharmony.aloha.test.proto.Testing.internal_static_com_eharmony_aloha_test_proto_PhotoProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getId() {
      return id_;
    }
    
    // optional int32 height = 2;
    public static final int HEIGHT_FIELD_NUMBER = 2;
    private int height_;
    public boolean hasHeight() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getHeight() {
      return height_;
    }
    
    // optional double aspect_ratio = 3;
    public static final int ASPECT_RATIO_FIELD_NUMBER = 3;
    private double aspectRatio_;
    public boolean hasAspectRatio() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public double getAspectRatio() {
      return aspectRatio_;
    }
    
    private void initFields() {
      id_ = 0L;
      height_ = 0;
      aspectRatio_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, height_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, aspectRatio_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, height_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, aspectRatio_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.eharmony.aloha.test.proto.Testing.PhotoProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.eharmony.aloha.test.proto.Testing.PhotoProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.eharmony.aloha.test.proto.Testing.PhotoProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.eharmony.aloha.test.proto.Testing.PhotoProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.eharmony.aloha.test.proto.Testing.PhotoProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.eharmony.aloha.test.proto.Testing.PhotoProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.eharmony.aloha.test.proto.Testing.PhotoProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.eharmony.aloha.test.proto.Testing.PhotoProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.eharmony.aloha.test.proto.Testing.PhotoProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.eharmony.aloha.test.proto.Testing.PhotoProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.eharmony.aloha.test.proto.Testing.PhotoProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.eharmony.aloha.test.proto.Testing.PhotoProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.eharmony.aloha.test.proto.Testing.internal_static_com_eharmony_aloha_test_proto_PhotoProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.eharmony.aloha.test.proto.Testing.internal_static_com_eharmony_aloha_test_proto_PhotoProto_fieldAccessorTable;
      }
      
      // Construct using com.eharmony.aloha.test.proto.Testing.PhotoProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        height_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        aspectRatio_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.eharmony.aloha.test.proto.Testing.PhotoProto.getDescriptor();
      }
      
      public com.eharmony.aloha.test.proto.Testing.PhotoProto getDefaultInstanceForType() {
        return com.eharmony.aloha.test.proto.Testing.PhotoProto.getDefaultInstance();
      }
      
      public com.eharmony.aloha.test.proto.Testing.PhotoProto build() {
        com.eharmony.aloha.test.proto.Testing.PhotoProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.eharmony.aloha.test.proto.Testing.PhotoProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.eharmony.aloha.test.proto.Testing.PhotoProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.eharmony.aloha.test.proto.Testing.PhotoProto buildPartial() {
        com.eharmony.aloha.test.proto.Testing.PhotoProto result = new com.eharmony.aloha.test.proto.Testing.PhotoProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.height_ = height_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.aspectRatio_ = aspectRatio_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.eharmony.aloha.test.proto.Testing.PhotoProto) {
          return mergeFrom((com.eharmony.aloha.test.proto.Testing.PhotoProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.eharmony.aloha.test.proto.Testing.PhotoProto other) {
        if (other == com.eharmony.aloha.test.proto.Testing.PhotoProto.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasHeight()) {
          setHeight(other.getHeight());
        }
        if (other.hasAspectRatio()) {
          setAspectRatio(other.getAspectRatio());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              height_ = input.readInt32();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              aspectRatio_ = input.readDouble();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 id = 1;
      private long id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getId() {
        return id_;
      }
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int32 height = 2;
      private int height_ ;
      public boolean hasHeight() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getHeight() {
        return height_;
      }
      public Builder setHeight(int value) {
        bitField0_ |= 0x00000002;
        height_ = value;
        onChanged();
        return this;
      }
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000002);
        height_ = 0;
        onChanged();
        return this;
      }
      
      // optional double aspect_ratio = 3;
      private double aspectRatio_ ;
      public boolean hasAspectRatio() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public double getAspectRatio() {
        return aspectRatio_;
      }
      public Builder setAspectRatio(double value) {
        bitField0_ |= 0x00000004;
        aspectRatio_ = value;
        onChanged();
        return this;
      }
      public Builder clearAspectRatio() {
        bitField0_ = (bitField0_ & ~0x00000004);
        aspectRatio_ = 0D;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.eharmony.aloha.test.proto.PhotoProto)
    }
    
    static {
      defaultInstance = new PhotoProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.eharmony.aloha.test.proto.PhotoProto)
  }
  
  public interface UserProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 id = 1;
    boolean hasId();
    long getId();
    
    // optional string name = 2;
    boolean hasName();
    String getName();
    
    // optional .com.eharmony.aloha.test.proto.GenderProto gender = 3;
    boolean hasGender();
    com.eharmony.aloha.test.proto.Testing.GenderProto getGender();
    
    // optional float bmi = 4;
    boolean hasBmi();
    float getBmi();
    
    // repeated .com.eharmony.aloha.test.proto.PhotoProto photos = 5;
    java.util.List<com.eharmony.aloha.test.proto.Testing.PhotoProto> 
        getPhotosList();
    com.eharmony.aloha.test.proto.Testing.PhotoProto getPhotos(int index);
    int getPhotosCount();
    java.util.List<? extends com.eharmony.aloha.test.proto.Testing.PhotoProtoOrBuilder> 
        getPhotosOrBuilderList();
    com.eharmony.aloha.test.proto.Testing.PhotoProtoOrBuilder getPhotosOrBuilder(
        int index);
  }
  public static final class UserProto extends
      com.google.protobuf.GeneratedMessage
      implements UserProtoOrBuilder {
    // Use UserProto.newBuilder() to construct.
    private UserProto(Builder builder) {
      super(builder);
    }
    private UserProto(boolean noInit) {}
    
    private static final UserProto defaultInstance;
    public static UserProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public UserProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.eharmony.aloha.test.proto.Testing.internal_static_com_eharmony_aloha_test_proto_UserProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.eharmony.aloha.test.proto.Testing.internal_static_com_eharmony_aloha_test_proto_UserProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getId() {
      return id_;
    }
    
    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .com.eharmony.aloha.test.proto.GenderProto gender = 3;
    public static final int GENDER_FIELD_NUMBER = 3;
    private com.eharmony.aloha.test.proto.Testing.GenderProto gender_;
    public boolean hasGender() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.eharmony.aloha.test.proto.Testing.GenderProto getGender() {
      return gender_;
    }
    
    // optional float bmi = 4;
    public static final int BMI_FIELD_NUMBER = 4;
    private float bmi_;
    public boolean hasBmi() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public float getBmi() {
      return bmi_;
    }
    
    // repeated .com.eharmony.aloha.test.proto.PhotoProto photos = 5;
    public static final int PHOTOS_FIELD_NUMBER = 5;
    private java.util.List<com.eharmony.aloha.test.proto.Testing.PhotoProto> photos_;
    public java.util.List<com.eharmony.aloha.test.proto.Testing.PhotoProto> getPhotosList() {
      return photos_;
    }
    public java.util.List<? extends com.eharmony.aloha.test.proto.Testing.PhotoProtoOrBuilder> 
        getPhotosOrBuilderList() {
      return photos_;
    }
    public int getPhotosCount() {
      return photos_.size();
    }
    public com.eharmony.aloha.test.proto.Testing.PhotoProto getPhotos(int index) {
      return photos_.get(index);
    }
    public com.eharmony.aloha.test.proto.Testing.PhotoProtoOrBuilder getPhotosOrBuilder(
        int index) {
      return photos_.get(index);
    }
    
    private void initFields() {
      id_ = 0L;
      name_ = "";
      gender_ = com.eharmony.aloha.test.proto.Testing.GenderProto.MALE;
      bmi_ = 0F;
      photos_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPhotosCount(); i++) {
        if (!getPhotos(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, gender_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, bmi_);
      }
      for (int i = 0; i < photos_.size(); i++) {
        output.writeMessage(5, photos_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, gender_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, bmi_);
      }
      for (int i = 0; i < photos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, photos_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.eharmony.aloha.test.proto.Testing.UserProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.eharmony.aloha.test.proto.Testing.UserProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.eharmony.aloha.test.proto.Testing.UserProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.eharmony.aloha.test.proto.Testing.UserProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.eharmony.aloha.test.proto.Testing.UserProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.eharmony.aloha.test.proto.Testing.UserProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.eharmony.aloha.test.proto.Testing.UserProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.eharmony.aloha.test.proto.Testing.UserProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.eharmony.aloha.test.proto.Testing.UserProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.eharmony.aloha.test.proto.Testing.UserProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.eharmony.aloha.test.proto.Testing.UserProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.eharmony.aloha.test.proto.Testing.UserProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.eharmony.aloha.test.proto.Testing.internal_static_com_eharmony_aloha_test_proto_UserProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.eharmony.aloha.test.proto.Testing.internal_static_com_eharmony_aloha_test_proto_UserProto_fieldAccessorTable;
      }
      
      // Construct using com.eharmony.aloha.test.proto.Testing.UserProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPhotosFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        gender_ = com.eharmony.aloha.test.proto.Testing.GenderProto.MALE;
        bitField0_ = (bitField0_ & ~0x00000004);
        bmi_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (photosBuilder_ == null) {
          photos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          photosBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.eharmony.aloha.test.proto.Testing.UserProto.getDescriptor();
      }
      
      public com.eharmony.aloha.test.proto.Testing.UserProto getDefaultInstanceForType() {
        return com.eharmony.aloha.test.proto.Testing.UserProto.getDefaultInstance();
      }
      
      public com.eharmony.aloha.test.proto.Testing.UserProto build() {
        com.eharmony.aloha.test.proto.Testing.UserProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.eharmony.aloha.test.proto.Testing.UserProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.eharmony.aloha.test.proto.Testing.UserProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.eharmony.aloha.test.proto.Testing.UserProto buildPartial() {
        com.eharmony.aloha.test.proto.Testing.UserProto result = new com.eharmony.aloha.test.proto.Testing.UserProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.gender_ = gender_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.bmi_ = bmi_;
        if (photosBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            photos_ = java.util.Collections.unmodifiableList(photos_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.photos_ = photos_;
        } else {
          result.photos_ = photosBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.eharmony.aloha.test.proto.Testing.UserProto) {
          return mergeFrom((com.eharmony.aloha.test.proto.Testing.UserProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.eharmony.aloha.test.proto.Testing.UserProto other) {
        if (other == com.eharmony.aloha.test.proto.Testing.UserProto.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasGender()) {
          setGender(other.getGender());
        }
        if (other.hasBmi()) {
          setBmi(other.getBmi());
        }
        if (photosBuilder_ == null) {
          if (!other.photos_.isEmpty()) {
            if (photos_.isEmpty()) {
              photos_ = other.photos_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensurePhotosIsMutable();
              photos_.addAll(other.photos_);
            }
            onChanged();
          }
        } else {
          if (!other.photos_.isEmpty()) {
            if (photosBuilder_.isEmpty()) {
              photosBuilder_.dispose();
              photosBuilder_ = null;
              photos_ = other.photos_;
              bitField0_ = (bitField0_ & ~0x00000010);
              photosBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPhotosFieldBuilder() : null;
            } else {
              photosBuilder_.addAllMessages(other.photos_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        for (int i = 0; i < getPhotosCount(); i++) {
          if (!getPhotos(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.eharmony.aloha.test.proto.Testing.GenderProto value = com.eharmony.aloha.test.proto.Testing.GenderProto.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                gender_ = value;
              }
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              bmi_ = input.readFloat();
              break;
            }
            case 42: {
              com.eharmony.aloha.test.proto.Testing.PhotoProto.Builder subBuilder = com.eharmony.aloha.test.proto.Testing.PhotoProto.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPhotos(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 id = 1;
      private long id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getId() {
        return id_;
      }
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // optional .com.eharmony.aloha.test.proto.GenderProto gender = 3;
      private com.eharmony.aloha.test.proto.Testing.GenderProto gender_ = com.eharmony.aloha.test.proto.Testing.GenderProto.MALE;
      public boolean hasGender() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.eharmony.aloha.test.proto.Testing.GenderProto getGender() {
        return gender_;
      }
      public Builder setGender(com.eharmony.aloha.test.proto.Testing.GenderProto value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        gender_ = value;
        onChanged();
        return this;
      }
      public Builder clearGender() {
        bitField0_ = (bitField0_ & ~0x00000004);
        gender_ = com.eharmony.aloha.test.proto.Testing.GenderProto.MALE;
        onChanged();
        return this;
      }
      
      // optional float bmi = 4;
      private float bmi_ ;
      public boolean hasBmi() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public float getBmi() {
        return bmi_;
      }
      public Builder setBmi(float value) {
        bitField0_ |= 0x00000008;
        bmi_ = value;
        onChanged();
        return this;
      }
      public Builder clearBmi() {
        bitField0_ = (bitField0_ & ~0x00000008);
        bmi_ = 0F;
        onChanged();
        return this;
      }
      
      // repeated .com.eharmony.aloha.test.proto.PhotoProto photos = 5;
      private java.util.List<com.eharmony.aloha.test.proto.Testing.PhotoProto> photos_ =
        java.util.Collections.emptyList();
      private void ensurePhotosIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          photos_ = new java.util.ArrayList<com.eharmony.aloha.test.proto.Testing.PhotoProto>(photos_);
          bitField0_ |= 0x00000010;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.eharmony.aloha.test.proto.Testing.PhotoProto, com.eharmony.aloha.test.proto.Testing.PhotoProto.Builder, com.eharmony.aloha.test.proto.Testing.PhotoProtoOrBuilder> photosBuilder_;
      
      public java.util.List<com.eharmony.aloha.test.proto.Testing.PhotoProto> getPhotosList() {
        if (photosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(photos_);
        } else {
          return photosBuilder_.getMessageList();
        }
      }
      public int getPhotosCount() {
        if (photosBuilder_ == null) {
          return photos_.size();
        } else {
          return photosBuilder_.getCount();
        }
      }
      public com.eharmony.aloha.test.proto.Testing.PhotoProto getPhotos(int index) {
        if (photosBuilder_ == null) {
          return photos_.get(index);
        } else {
          return photosBuilder_.getMessage(index);
        }
      }
      public Builder setPhotos(
          int index, com.eharmony.aloha.test.proto.Testing.PhotoProto value) {
        if (photosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhotosIsMutable();
          photos_.set(index, value);
          onChanged();
        } else {
          photosBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setPhotos(
          int index, com.eharmony.aloha.test.proto.Testing.PhotoProto.Builder builderForValue) {
        if (photosBuilder_ == null) {
          ensurePhotosIsMutable();
          photos_.set(index, builderForValue.build());
          onChanged();
        } else {
          photosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addPhotos(com.eharmony.aloha.test.proto.Testing.PhotoProto value) {
        if (photosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhotosIsMutable();
          photos_.add(value);
          onChanged();
        } else {
          photosBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addPhotos(
          int index, com.eharmony.aloha.test.proto.Testing.PhotoProto value) {
        if (photosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhotosIsMutable();
          photos_.add(index, value);
          onChanged();
        } else {
          photosBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addPhotos(
          com.eharmony.aloha.test.proto.Testing.PhotoProto.Builder builderForValue) {
        if (photosBuilder_ == null) {
          ensurePhotosIsMutable();
          photos_.add(builderForValue.build());
          onChanged();
        } else {
          photosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addPhotos(
          int index, com.eharmony.aloha.test.proto.Testing.PhotoProto.Builder builderForValue) {
        if (photosBuilder_ == null) {
          ensurePhotosIsMutable();
          photos_.add(index, builderForValue.build());
          onChanged();
        } else {
          photosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllPhotos(
          java.lang.Iterable<? extends com.eharmony.aloha.test.proto.Testing.PhotoProto> values) {
        if (photosBuilder_ == null) {
          ensurePhotosIsMutable();
          super.addAll(values, photos_);
          onChanged();
        } else {
          photosBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearPhotos() {
        if (photosBuilder_ == null) {
          photos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          photosBuilder_.clear();
        }
        return this;
      }
      public Builder removePhotos(int index) {
        if (photosBuilder_ == null) {
          ensurePhotosIsMutable();
          photos_.remove(index);
          onChanged();
        } else {
          photosBuilder_.remove(index);
        }
        return this;
      }
      public com.eharmony.aloha.test.proto.Testing.PhotoProto.Builder getPhotosBuilder(
          int index) {
        return getPhotosFieldBuilder().getBuilder(index);
      }
      public com.eharmony.aloha.test.proto.Testing.PhotoProtoOrBuilder getPhotosOrBuilder(
          int index) {
        if (photosBuilder_ == null) {
          return photos_.get(index);  } else {
          return photosBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.eharmony.aloha.test.proto.Testing.PhotoProtoOrBuilder> 
           getPhotosOrBuilderList() {
        if (photosBuilder_ != null) {
          return photosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(photos_);
        }
      }
      public com.eharmony.aloha.test.proto.Testing.PhotoProto.Builder addPhotosBuilder() {
        return getPhotosFieldBuilder().addBuilder(
            com.eharmony.aloha.test.proto.Testing.PhotoProto.getDefaultInstance());
      }
      public com.eharmony.aloha.test.proto.Testing.PhotoProto.Builder addPhotosBuilder(
          int index) {
        return getPhotosFieldBuilder().addBuilder(
            index, com.eharmony.aloha.test.proto.Testing.PhotoProto.getDefaultInstance());
      }
      public java.util.List<com.eharmony.aloha.test.proto.Testing.PhotoProto.Builder> 
           getPhotosBuilderList() {
        return getPhotosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.eharmony.aloha.test.proto.Testing.PhotoProto, com.eharmony.aloha.test.proto.Testing.PhotoProto.Builder, com.eharmony.aloha.test.proto.Testing.PhotoProtoOrBuilder> 
          getPhotosFieldBuilder() {
        if (photosBuilder_ == null) {
          photosBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.eharmony.aloha.test.proto.Testing.PhotoProto, com.eharmony.aloha.test.proto.Testing.PhotoProto.Builder, com.eharmony.aloha.test.proto.Testing.PhotoProtoOrBuilder>(
                  photos_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          photos_ = null;
        }
        return photosBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.eharmony.aloha.test.proto.UserProto)
    }
    
    static {
      defaultInstance = new UserProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.eharmony.aloha.test.proto.UserProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_eharmony_aloha_test_proto_PhotoProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_eharmony_aloha_test_proto_PhotoProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_eharmony_aloha_test_proto_UserProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_eharmony_aloha_test_proto_UserProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nUser.proto\022\035com.eharmony.aloha.test.pr" +
      "oto\">\n\nPhotoProto\022\n\n\002id\030\001 \002(\003\022\016\n\006height\030" +
      "\002 \001(\005\022\024\n\014aspect_ratio\030\003 \001(\001\"\251\001\n\tUserProt" +
      "o\022\n\n\002id\030\001 \002(\003\022\014\n\004name\030\002 \001(\t\022:\n\006gender\030\003 " +
      "\001(\0162*.com.eharmony.aloha.test.proto.Gend" +
      "erProto\022\013\n\003bmi\030\004 \001(\002\0229\n\006photos\030\005 \003(\0132).c" +
      "om.eharmony.aloha.test.proto.PhotoProto*" +
      "#\n\013GenderProto\022\010\n\004MALE\020\001\022\n\n\006FEMALE\020\002B\tB\007" +
      "Testing"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_eharmony_aloha_test_proto_PhotoProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_eharmony_aloha_test_proto_PhotoProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_eharmony_aloha_test_proto_PhotoProto_descriptor,
              new java.lang.String[] { "Id", "Height", "AspectRatio", },
              com.eharmony.aloha.test.proto.Testing.PhotoProto.class,
              com.eharmony.aloha.test.proto.Testing.PhotoProto.Builder.class);
          internal_static_com_eharmony_aloha_test_proto_UserProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_eharmony_aloha_test_proto_UserProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_eharmony_aloha_test_proto_UserProto_descriptor,
              new java.lang.String[] { "Id", "Name", "Gender", "Bmi", "Photos", },
              com.eharmony.aloha.test.proto.Testing.UserProto.class,
              com.eharmony.aloha.test.proto.Testing.UserProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
