/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.eharmony.aloha.audit.impl.avro;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface AlohaScoreProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"AlohaScoreProtocol\",\"namespace\":\"com.eharmony.aloha.audit.impl.avro\",\"types\":[{\"type\":\"record\",\"name\":\"ModelId\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"name\",\"type\":[\"null\",\"string\"],\"default\":null}]},{\"type\":\"record\",\"name\":\"Score\",\"fields\":[{\"name\":\"model\",\"type\":[\"null\",\"ModelId\"],\"default\":null},{\"name\":\"value\",\"type\":[\"null\",\"boolean\",\"int\",\"long\",\"float\",\"double\",\"string\",{\"type\":\"array\",\"items\":[\"boolean\",\"int\",\"long\",\"float\",\"double\",\"string\"]}],\"default\":null},{\"name\":\"subvalues\",\"type\":[{\"type\":\"array\",\"items\":\"Score\"},\"null\"],\"default\":[]},{\"name\":\"errorMsgs\",\"type\":[{\"type\":\"array\",\"items\":\"string\"},\"null\"],\"default\":[]},{\"name\":\"missingVarNames\",\"type\":[{\"type\":\"array\",\"items\":\"string\"},\"null\"],\"default\":[]},{\"name\":\"prob\",\"type\":[\"null\",\"float\"],\"default\":null}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends AlohaScoreProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = com.eharmony.aloha.audit.impl.avro.AlohaScoreProtocol.PROTOCOL;
  }
}